#!/bin/bash

echo "=========================================="
echo "TestFlight Build Başlatma Rehberi"
echo "=========================================="
echo ""
echo "Adım 1: EAS Proje Yapılandırması"
echo "Terminal'de şu komutu çalıştırın:"
echo ""
echo "  cd /Users/emreguneri/Berber"
echo "  eas build:configure"
echo ""
echo "Soru sorulduğunda 'y' tuşuna basın"
echo ""
echo "Adım 2: Build Başlatma"
echo "Yapılandırma tamamlandıktan sonra:"
echo ""
echo "  eas build --platform ios --profile production"
echo ""
echo "=========================================="
echo ""
echo "NOT: İlk kez build yapıyorsanız:"
echo "  - Apple Developer hesabı gerekli"
echo "  - App Store Connect'te uygulama oluşturulmalı"
echo "  - Build 20-30 dakika sürebilir"
echo ""
