#!/bin/bash

echo "=== TestFlight Build Başlatılıyor ==="
echo ""
echo "1. EAS Proje Yapılandırması:"
echo "   eas build:configure"
echo ""
echo "2. Production Build (TestFlight için):"
echo "   eas build --platform ios --profile production"
echo ""
echo "3. Build Durumunu Kontrol Et:"
echo "   eas build:list"
echo ""
echo "4. Build Tamamlandıktan Sonra Otomatik Submit:"
echo "   eas submit --platform ios --latest"
echo ""
echo "=== Adımlar ==="
echo "1. Önce 'eas build:configure' komutunu çalıştırın"
echo "2. Sonra 'eas build --platform ios --profile production' ile build başlatın"
echo "3. Build tamamlandıktan sonra App Store Connect'te TestFlight sekmesinden yayınlayın"
